### ISSUE TITLE
tf cannot find the transformation

### ISSUE THREAD

**Issue by zengzhen** [h2r/baxter_h2r_packages#3]
Hi, 
I'm trying this out for calibrating my kinect with the baxter.
When I try to view the transformation using:
rosrun tf tf_echo /world /camera

I got the error as shown below:
Failure at 1406671364.533850147
Exception thrown:Could not find a connection between 'world' and 'camera_link' because they are not part of the same tree.Tf has two or more unconnected trees.

Can you help resolve this issue? Thanks a lot!

**Comment by brawner** [comment]
Could you provide more information about this error? 

Did you run the setup_robot_left.sh script?

Can you confirm that your bundle is viewable in both the left_hand_camera and the kinect image?

Does this error come up constantly, or do you only see it published once or twice. If it's a few times, that's ok. It just means that it took a few minutes for both cameras to get synced together. If it's constant, then I suspect that you need both cameras to get a good view of your bundle.

**Comment by zengzhen** [comment]
Yes, I did run the setup_robot_left.sh script, and the terminal showed "robot enabled". Could you explain a bit on what this script does?

The markers are viewable in both left_hand_camera and the kinect, I confirmed these by `image_view` those published images, but the error came up constantly.

 From the other terminal window which launched the calibration tool (baxter_bundle_calibrate.launch), it was constantly publishing the transform between /reference/left_hand_camera and ar_alvar_marker8(something similar to this), is this the only transform the calibration tool is supposed to be publishing or there should be more?

And shall I use `rosrun tf tf_echo /world /camera` or `rosrun tf tf_echo /world /camera_link` to view the transform?

Thanks!

**Comment by brawner** [comment]
If it publishes between left_hand_camera and ar_alvar_marker8, but not
ar_alvar_marker8 to camera_link, that means that the kinect is not viewing
the markers correctly. For it to work the best, they need to be
sufficiently large in the kinect's image. In RViz there should be two sets
of markers published. In Rviz, add a Marker object and select the topics.
There is a visualization_markers topic and a
visualization_markers_calibrated. The calibrated one is for the markers
detected by the left_hand_camera, the other one is for the kinect. If
visualization_markers doesn't show up it suggests that the kinect can't
properly view them.

If you print the print the markers out at 45 mm width, then the kinect
should be no more than 1 meter away. If you need the kinect to be further
away, you'll have to print the markers out larger and modify the
baxter_bundle_calibrate.launch appropriately.

**Comment by zengzhen** [comment]
Sorry for the late response.
Now I've moved the Kinect closer to the markers, and I can get the transform from tf. Thanks a lot!
